# Site
name: "Xyz Blog"
title: "Xyz Blog"
description: "We spend so much of our lives looking, but never, never seeing."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /drafts
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bross:
    name: "Bob Ross"
    display_name: Bob
    avatar_url: https://upload.wikimedia.org/wikipedia/commons/0/05/Robert_N._%22Bob%22_Ross_1960s_Air_Force.jpg
    web: https://www.bobrosslipsum.com/
    twitter: https://twitter.com/BobRossLipsum
    description: "The creator and host of the universe, when he would draw nature would be thus."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
